### PR TITLE
Better maps

### PR DESCRIPTION
**Pull request by lajonat**
Create better texture maps for planets, create biome maps

### CODE REVIEW

**Comment by StollD** [comment]
Thanks for your contributions!

Your second commit looks good to me, however, please revert your first commit. We really shouldn't create a map that is different from what the PQS will show. The reason why all bodies except vertex planet have blank maps is, that we don't have prefabs for all bodies. If a body doesn't have a prefab, this fallback gets applied and it has a solid color https://github.com/Kopernicus/Stellarator/blob/master/PlanetData/pqs/EverythingElse.cfg

Nevertheless, I would be interested in how one of the maps generated with this algorithm looks like.

**Comment by lajonat** [comment]
Well, I figured a colored map would be more aesthetic than a chrome ball. It's also quite hard to actually play with these kinds of planets, because you can't really tell how the surface looks unless you're already on it.

I've attached a sample of the maps generated by my changes:
cresos_height
cresos_normals
cresos_texture
cresos_biomes

**Comment by StollD** [comment]
Maybe just add a HeightColorMap mod to the `EverythingElse` template? I think that would solve the problem of having a solid color ball, while allowing us to keep the map export as stockalike as possible.

**Comment by lajonat** [comment]
Adding a HeightColorMap colors the terrain up close, but still when looking at the map view it looks colorless.
Anyway, I reverted the textures, and kept only the biome map.

**Pull request merged**
